baseURL = "https://anhcodes.dev/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "anhcodes"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
resumeURL = "resume"
contactLink = "contact"
copyright = "All right reserved copyright © Anh Chu 2022"
footerLogo = "images/site-navigation/logo-new.png"
# We're using formspree.io for form handling, paste your formspree url below
getformURL  = "https://getform.io/f/a5b7b431-b84e-4ac4-b065-d82f4ae85ee9"
googleAnalytics = "G-9145PR72NN"
logo = "images/site-navigation/logo-new.png"

[params.address]
address = "Seattle, Washington"
linkedin = "linkedin.com/in/anhhchu/"
github = "github.com/anhhchu"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"


# Social icons
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/jasminmay12/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/anhhchu/"
weight = 2
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/anhhchu"
weight = 3