baseURL = "https://xxxx/"
languageCode = "en-us"
paginate = 27
theme = "portio"
title = "xxxx"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3
[[menu.main]]
name = "Experiences"
url = "#resume"
weight = 4
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 5
# [[menu.main]]
# name = "Projects"
# url = "#portfolio"
# weight = 6
[[menu.main]]
name = "Testimonials"
url = "#testimonial"
weight = 7
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
resumeURL = "resume"
contactLink = "contact"
copyright = "All right reserved copyright © Anh Chu 2022"
footerLogo = "images/site-navigation/logonew.png"
# We're using formspree.io for form handling, paste your formspree url below
getformURL  = "https://getform.io/f/xxxxx"
googleAnalytics = "G-xxxx"
logo = "images/favicon.png"


[params.address]
address = "xxxx"
linkedin = "Connect with me"
github = "View my work"
resume = "View my experiences"

# [params.map]
APIkey = "xxxx"
APIkey = "xxxx"
latitude = "xxxx"
longitude = "xxxx"
latitude1 = "xxxx"
longitude1 = "xxxx"
pinImage = "images/pin.png"


# Social icons
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/xxxx/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/xxxx/"
weight = 2
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/xxxx"
weight = 3

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    # lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'witchhazel'
    tabWidth = 4

# [outputFormats.Algolia]
# baseName = "algolia"
# isPlainText = true
# mediaType = "application/json"
# notAlternative = true

# [params.algolia]
# vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
# params = ["categories", "tags"]

# [outputs]
# home = ["HTML", "RSS", "Algolia"]